# Generated by Django 4.1.5 on 2023-01-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
