# Generated by Django 4.1.5 on 2023-01-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signupemail', models.CharField(max_length=100)),
                ('signuppassword', models.CharField(max_length=100)),
            ],
        ),
    ]
