# Generated by Django 4.1.5 on 2023-01-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginemail', models.CharField(max_length=100)),
                ('loginpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
