# Generated by Django 4.1.5 on 2023-01-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
